FROM golang:1.25-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o poker-club ./cmd/poker-club

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/poker-club .

EXPOSE 8080

CMD ["./poker-club"]